alias update="sudo apt update && sudo apt upgrade -y"
alias i3conf="vim ~/.config/i3/config"
alias ssp="sudo pm-suspend"
alias inst="sudo apt install"
alias sht="shutdown now"
alias visualize="padsp synaesthesia line"
alias slsk="cd Downloads/Install_files/ && ./Soulseek*"
alias wall="wal -n -g -i"
